url: https://hashtaggeeks.com
baseurl:
sass:
  load_paths:
    - _sass
    - node_modules
exclude: 
  - node_modules
  - Makefile
  - package.json
  - package-lock.json
  - Readme.txt
plugins: [jekyll-paginate-v2]
permalink: /posts/:title.html
pagination:
  enabled: true
  per_page: 9
  permalink: '/page/page:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page
